name: Deploy to Google Cloud

on:
  push:
    branches:
      - test-telegram-bot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        run: |
          curl -o google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-372.0.0-linux-x86_64.tar.gz
          tar -xf google-cloud-sdk.tar.gz
          ./google-cloud-sdk/install.sh --quiet
          echo "${{ secrets.GCLOUD_AUTH }}" > /tmp/gcloud.json
          ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=/tmp/gcloud.json
          ./google-cloud-sdk/bin/gcloud config set project cdtest-406103

      - name: Build Docker image
        run: |
          docker build -t telegram-bot-sample-img .

      - name: Configure Docker and push image
        run: |
          ./google-cloud-sdk/bin/gcloud auth configure-docker
          docker tag telegram-bot-sample-img gcr.io/cdtest-406103/telegram-bot-sample-img
          docker push gcr.io/cdtest-406103/telegram-bot-sample-img

      - name: Deploy to Google Cloud Run
        run: |
          ./google-cloud-sdk/bin/gcloud run deploy telegram-bot-sample-service \
            --image=gcr.io/cdtest-406103/telegram-bot-sample-img \
            --platform=managed \
            --region=asia-southeast1 \
            --allow-unauthenticated
  send-notification-successful:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ success() && needs.deploy.result == 'success' }}
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}"
        run: |
          curl -X POST \
            https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="🎉 <b>Cloud Run CI/CD Template</b> Deployment was successful!
            Your amazing tool is now available for everyone! 🚀✨" \
            -d parse_mode=HTML

  send-notification-failed:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ failure() && needs.deploy.result == 'failure' }}
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}"
        run: |
          curl -X POST \
            https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="❌ Oh no! <b>Cloud Run CI/CD Template</b> Deployment failed!
            There might be something wrong with the process. 
            Please check it out! 🛠️🔍" \
            -d parse_mode=HTML